# Generated by Django 2.2.10 on 2020-03-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=32)),
                ('amount_required', models.IntegerField()),
                ('major', models.CharField(choices=[('', 'Choose...'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('CHEM', 'Chemistry'), ('OTH', 'Other')], max_length=3)),
                ('years_in_college', models.IntegerField()),
                ('other', models.CharField(max_length=64)),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
