# Generated by Django 2.2.11 on 2020-03-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200329_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='amount_required',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='other',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='years_in_college',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_TB',
            field=models.EmailField(default='N/A', help_text='Please fill in at least 1 form of contact', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.CharField(choices=[('', 'Choose'), ('Fr', 'Freshman'), ('So', 'Sophmore'), ('Jr', 'Junior'), ('Sr', 'Senior'), ('M', 'Masters'), ('P', 'Phd')], default='N/A', max_length=20, verbose_name='Level/Year'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='other_TB1',
            field=models.CharField(default='N/A', help_text='Please fill in at least 1 form of contact', max_length=32, verbose_name='Other Contact Type'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='other_TB2',
            field=models.CharField(default='N/A', max_length=32, verbose_name='Other Contact Information'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_TB',
            field=models.CharField(default='N/A', help_text='Please fill in at least 1 form of contact', max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default='N/A', max_length=32, verbose_name='College/University'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='agree',
            field=models.BooleanField(verbose_name='Do you agree to the terms and conditions listed below?'),
        ),
    ]
